@WeatherApp_HostAddress = https://localhost:7149

GET {{WeatherApp_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{WeatherApp_HostAddress}}/weatherforecast?cities=London&cities=Syndey

###


GET {{WeatherApp_HostAddress}}/weatherforecast?cityName=New%20York

###

GET {{WeatherApp_HostAddress}}/locations

###
